[project]
name = "backend"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "mlflow",
    "loguru",
    "pandas",
    "numpy",
    "scikit-learn",
    "xgboost",
    "optuna",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "jupyter",
    "matplotlib",
    "seaborn",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--pyargs",
]

testpaths = [
    "tests",
]
