[project]
name = "backend"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "mlflow",
]

[tool.setuptools]
packages = ["src"]

[project.optional-dependencies]
dev = [
    "pytest",
    "jupyter",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
    "--pyargs",
]

testpaths = [
    "tests",
]
